apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: traefik

resources:
- namespace.yml
# - pod-monitor.yml
- middlewares.yml
# - ingress-class.yml

helmCharts:
- name: traefik
  includeCRDs: true
  valuesFile: values.yml
  releaseName: traefik
  namespace: traefik
  version: 22.0.0
  repo: https://helm.traefik.io/traefik