apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      imagePullSecrets:
        - name: ecr-secert
      containers:
        - name: my-app
          image: 842675998483.dkr.ecr.us-east-2.amazonaws.com/harshitha:15e8ec45e4bab5e592c3a3adbfa3e7b4f97bf0b9
          ports:
            - containerPort: 8080
