apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      imagePullSecrets:
        - name: ecr-secert
      containers:
        - name: my-app
          image: 842675998483.dkr.ecr.us-east-2.amazonaws.com/harshitha:65fb0e290c170265d6c6ea2ff749a8f3a6392017
          ports:
            - containerPort: 8080
