apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      imagePullSecrets:
        - name: ecr-secert
      containers:
        - name: my-app
          image: 842675998483.dkr.ecr.us-east-2.amazonaws.com/harshitha:bd9b61742362fbbfec91aa00606362d0550b255d
          ports:
            - containerPort: 8080
            
