apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      imagePullSecrets:
        - name: ecr-secert
      containers:
        - name: my-app
          image: 842675998483.dkr.ecr.us-east-2.amazonaws.com/harshitha:7a6240e5fc75d482c7a85d539b209d3ec2896f27
          ports:
            - containerPort: 8080
            
