apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      imagePullSecrets:
        - name: ecr-secert
      containers:
        - name: my-app
          image: 842675998483.dkr.ecr.us-east-2.amazonaws.com/harshitha:538f79beb5a903cf61edc921a6b391982ccefd26
          ports:
            - containerPort: 8080
