pipeline {
    agent any

    environment {
        DOCKER_IMAGE = "${ECR_REPO_URI}:${IMAGE_TAG}"
        AWS_REGION = "us-east-2"
        ECR_REPO_URI = "842675998483.dkr.ecr.us-east-2.amazonaws.com/harshitha"
        GIT_REPO_URL = 'https://github.com/harshitha716/nginx.git'
        GIT_BRANCH = 'main' // Set the branch you want to deploy from
        ECR_REGION = 'us-east-2' // Replace with your AWS region
        AWS_ACCESS_KEY_ID =  'AKIA4IM3HJ4JRD3KTLLL'
        AWS_SECRET_ACCESS_KEY = 'WX5+6wyw+rEuMWiCNCzmNpOgnz4mRH6AyQz4+FJi'
        AWS_DEFAULT_REGION = 'us-east-2'
        ARGOCD_SERVER = 'https://localhost:8080'
        ARGOCD_APP_NAME = 'test'
        DEPLOYMENT_NAME = 'my-app'
        CONTAINER_NAME = 'my-app'
        IMAGE_TAG = "${GIT_COMMIT}" 
        DEPLOYMENT_YAML_PATH = 'nginx-app/deployment.yaml'
    }

    stages {
        stage('Checkout Code') {
            steps {
                checkout([$class: 'GitSCM', 
                    branches: [[name: "*/${GIT_BRANCH}"]], 
                    userRemoteConfigs: [[url: "${GIT_REPO_URL}"]]
                ])
            }
        }

        stage('Build and Push Docker Image') {
            steps {
                script {
                    // Use the correct path now
                    sh 'cd nginx-app && docker build -t ${DOCKER_IMAGE} .'
                    sh 'aws ecr get-login-password --region ${ECR_REGION} | docker login --username AWS --password-stdin ${ECR_REPO_URI}'
                    sh 'docker push ${DOCKER_IMAGE}'
                }
            }
        }
        stage('Update deployment.yaml with new image') {
            steps {
                script {
                    // Update the image in the deployment.yaml with the new tag
                    sh """
                        sed -i 's|image: .*|image: ${DOCKER_IMAGE}|' ${DEPLOYMENT_YAML_PATH}
                    """
                }
            }
        }

        stage('Commit Updated deployment.yaml') {
            steps {
                script {
                    // Commit the updated deployment.yaml back to the Git repository
                    sh """
                        git config --global user.name "harshitha716"
                        git config --global user.email "harshithapendiyala0812@gmail.com"
                        git add ${DEPLOYMENT_YAML_PATH}
                        git commit -m "Update deployment.yaml with new image: ${DOCKER_IMAGE}"
                        git push ${GIT_REPO_URL} HEAD:${GIT_BRANCH}  // Push changes to the correct branch
                    """
                }
            }
        }

                   
    post {
        always {
            cleanWs()
        }
    }
}
