installCRDs: true

global:
  leaderElection:
    namespace: cert-manager

prometheus:
  servicemonitor:
    enabled: true

resources:
  requests:
    cpu: 10m
    memory: 64Mi

webhook:
  resources:
    requests:
      cpu: 10m
      memory: 32Mi

cainjector:
  resources:
    requests:
      cpu: 10m
      memory: 64Mi
